[package]
name = "oweka"
description = "Performant TUI tool that lets you delete artifact directories (e.g. node_modules, target)"
repository = "https://github.com/ByteAtATime/oweka.git"
homepage = "https://github.com/ByteAtATime/oweka"
version = "0.1.2"
edition = "2024"
license = "MIT"

[dependencies]
crossterm = "0.29.0"
dirs = "6"
ratatui = "0.30.2"

[dev-dependencies]
criterion = "0.8"
filetime = "0.2.29"
tempfile = "3.27.0"

[[bench]]
name = "scan"
harness = false

[profile.release]
codegen-units = 1
lto = true

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = true
